---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: container-injector-mwc
  labels:
    app.kubernetes.io/name: container-injector
webhooks:
  - name: container-injector.uthng.me
    clientConfig:
      service:
        name: container-injector-svc
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["deployments", "jobs", "pods", "statefulsets"]
    namespaceSelector: {}
