---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-injector
  labels:
    app.kubernetes.io/name: container-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: container-injector-clusterrole
  labels:
    app.kubernetes.io/name: container-injector
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs:
    - "get"
    - "list"
    - "watch"
    - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: container-injector-binding
  labels:
    app.kubernetes.io/name: container-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: container-injector-clusterrole
subjects:
- kind: ServiceAccount
  name: container-injector
  namespace: container-injector
