apiVersion: v1
kind: Service
metadata:
  name: container-injector-svc
  labels:
    app.kubernetes.io/name: container-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/name: container-injector
