apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      annotations:
        container-injector.uthng.me/inject: "true"
        container-injector.uthng.me/name: "git-sync"
        container-injector.uthng.me/image: "k8s.gcr.io/git-sync:v3.1.3"
        container-injector.uthng.me/env-GIT_SYNC_REPO: "https://github.com/kubernetes/git-sync.git"
        container-injector.uthng.me/env-GIT_SYNC_DEST: "git-sync"
        container-injector.uthng.me/env-GIT_SYNC_WAIT: "10"
        container-injector.uthng.me/volume-mount-markdown: "/tmp/git"
        container-injector.uthng.me/volume-source-markdown: '{"emptyDir": {}}'
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
